# Generated by Django 4.2.6 on 2023-10-18 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Age', models.CharField(max_length=200)),
                ('Budget', models.CharField(max_length=200)),
                ('Adress', models.CharField(max_length=300, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=1500, verbose_name='message')),
            ],
        ),
    ]
