# Generated by Django 4.2.6 on 2023-10-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientInfo',
        ),
    ]
